name: classical_ly
description: A repertoire and performance journal for classical musicians.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.12.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
